#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: mint each MCP credential, store it in the macOS login keychain, and
# wire the server that uses it -- in that order, and only that order.
#
# Nothing is written to .env: that is the point. Each secret goes straight into
# the login keychain, where mcp-keychain-token.sh reads it at connect time.
# ENV_FILE points at a path we never write, and ask_token pre-seeds from the
# keychain so "Enter keeps current" means the stored token, not the empty
# string the library would otherwise read out of /dev/null.
#
# Why the order is store -> probe -> wire: an Authorization header suppresses
# omp's managed OAuth credential for that URL, and a failing header command does
# not give it back (measured 2026-09-01 -- sentry with a header and no stored
# item did not mount at all, while the same entry without the header returned
# its org). So the header is written only after the endpoint has accepted the
# token with a 200. A rejected token leaves mcp.json untouched and that server
# still on working OAuth.
#
# Which endpoints actually accept a static bearer is unproven for sentry and
# notion: a fabricated token returns 401 from an OAuth-only endpoint and from a
# bearer endpoint alike, so the probes below are the first real evidence either
# way. Notion documents static tokens for api.notion.com, not mcp.notion.com;
# Slack documents the user token as a type but not its acceptance here.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4
ENV_FILE="/dev/null"

MCP_JSON="$HOME/.omp/agent/mcp.json"
RESOLVER='!$HOME/.omp/agent/scripts/mcp-keychain-token.sh'

# ask_token VAR SERVICE "Prompt" reads a secret, defaulting to whatever is
# already in the keychain so a re-run can press Enter and move on.
ask_token() {
	local var="$1" service="$2" prompt="$3" current input
	current=$(security find-generic-password -w -s "$service" -a omp 2>/dev/null || true)
	if [[ -n $current ]]; then
		note "an item is already stored for $service (${#current} chars)"
		printf '  %s%s%s %s[Enter keeps the stored one]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
	else
		printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
	fi
	read -rs input || true
	printf '\n'
	[[ -z $input && -n $current ]] && input="$current"
	printf -v "$var" '%s' "$input"
}

# store_keychain SERVICE VALUE upserts a generic password under account "omp".
# No -A: the ACL then covers the `security` binary, which is also the reader in
# mcp-keychain-token.sh, so reads stay unprompted without opening the item to
# every process. The value passes through argv for the few ms `security` runs;
# on a single-user machine that is not the weak link, since any process running
# as this user can read the item back anyway.
store_keychain() {
	local service="$1" value="$2"
	if [[ -z $value ]]; then
		warn "nothing entered; leaving $service unchanged"
		SKIPPED+=("keychain item $service")
		return 1
	fi
	if security add-generic-password -s "$service" -a omp -w "$value" -U 2>/dev/null; then
		printf '  %s✓ stored%s %s in the login keychain\n' "$GREEN" "$RESET" "$service"
		return 0
	fi
	warn "could not write $service to the keychain"
	SKIPPED+=("keychain item $service")
	return 1
}

# probe_mcp URL SERVICE: initialize against the real endpoint with the stored
# token. Returns success only on HTTP 200, which is what gates wiring.
probe_mcp() {
	local url="$1" service="$2" auth status
	auth=$("$HOME/.omp/agent/scripts/mcp-keychain-token.sh" "$service" 2>/dev/null) || {
		warn "no token stored for $service; nothing to probe"
		return 1
	}
	status=$(curl -s -o /dev/null -w '%{http_code}' -X POST "$url" \
		-H 'Content-Type: application/json' \
		-H 'Accept: application/json, text/event-stream' \
		-H "Authorization: $auth" \
		-d '{"jsonrpc":"2.0","id":1,"method":"initialize","params":{"protocolVersion":"2025-06-18","capabilities":{},"clientInfo":{"name":"omp-wizard","version":"1"}}}')
	if [[ $status == 200 ]]; then
		printf '  %s✓ %s accepted the token%s (HTTP 200)\n' "$GREEN" "$url" "$RESET"
		return 0
	fi
	warn "$url answered HTTP $status with the stored token"
	return 1
}

# wire_header SERVER SERVICE points a server's Authorization header at the
# keychain item and clears "enabled": false. Called only after a 200.
wire_header() {
	local server="$1" service="$2"
	if MCP_SERVER="$server" MCP_CMD="$RESOLVER $service" python3 - "$MCP_JSON" <<'PY'
import json, os, sys

path = sys.argv[1]
with open(path) as fh:
    cfg = json.load(fh)
server = cfg.get("mcpServers", {}).get(os.environ["MCP_SERVER"])
if server is None:
    sys.exit(f"no {os.environ['MCP_SERVER']} server in mcp.json")
server.setdefault("headers", {})["Authorization"] = os.environ["MCP_CMD"]
server.pop("enabled", None)
with open(path, "w") as fh:
    json.dump(cfg, fh, indent=2)
    fh.write("\n")
PY
	then
		printf '  %s✓ wired%s %s → %s\n' "$GREEN" "$RESET" "$server" "$service"
	else
		warn "could not edit $MCP_JSON for $server"
		SKIPPED+=("point $server's Authorization header at $service by hand")
	fi
}

# keep_oauth SERVER: what to say when a probe fails. The token stays in the
# keychain, unused; the server stays on the OAuth credential omp already holds.
keep_oauth() {
	warn "leaving $1 on OAuth — mcp.json untouched, so nothing regressed"
	note "the token is stored but unused; fix the token type or scopes and re-run"
	SKIPPED+=("$1: endpoint rejected the stored token, still on OAuth")
}

banner "omp MCP credentials → macOS login keychain"

# ── Stage 1 ───────────────────────────────────────────────────────────────
stage "Notion: internal integration token"
say "Notion documents static tokens for its REST API; whether the hosted MCP"
say "endpoint accepts one is what the probe at the end of this stage settles."
open_url "https://www.notion.so/profile/integrations"
step "Click 'New internal integration'."
step "Name it (e.g. omp), pick the workspace, create it."
step "On the Configuration tab, reveal and copy the Internal Integration Secret (starts ntn_)."
ask_token NOTION_TOKEN "omp/notion-mcp-token" "Paste the Notion integration secret:"
if store_keychain "omp/notion-mcp-token" "$NOTION_TOKEN"; then
	if probe_mcp "https://mcp.notion.com/mcp" "omp/notion-mcp-token"; then
		wire_header notion "omp/notion-mcp-token"
	else
		keep_oauth notion
	fi
fi
warn "An integration sees only pages explicitly shared with it."
step "In Notion: open each page/database → ⋯ menu → Connections → add your integration."
note "Skip this and the tools connect but return nothing."
pause "Shared at least one page?"

# ── Stage 2 ───────────────────────────────────────────────────────────────
stage "Sentry: user auth token"
say "sentry currently works on OAuth, so this stage only changes anything if"
say "mcp.sentry.dev accepts a user auth token as a bearer. The probe decides."
open_url "https://kpk-ee.sentry.io/settings/account/api/auth-tokens/"
step "Click 'Create New Token'."
step "Grant the scopes mcp.sentry.dev advertises: org:read, project:write, team:write, event:write."
step "Create it, then copy the token — shown once, starts sntryu_."
ask_token SENTRY_TOKEN "omp/sentry-mcp-token" "Paste the Sentry user auth token:"
if store_keychain "omp/sentry-mcp-token" "$SENTRY_TOKEN"; then
	if probe_mcp "https://mcp.sentry.dev/mcp" "omp/sentry-mcp-token"; then
		wire_header sentry "omp/sentry-mcp-token"
	else
		keep_oauth sentry
		note "to drop the unused token: security delete-generic-password -s omp/sentry-mcp-token -a omp"
	fi
fi

# ── Stage 3 ───────────────────────────────────────────────────────────────
stage "Slack: internal app + user token"
say "Slack supports neither dynamic client registration nor anonymous MCP use,"
say "so it needs an internal app in your workspace and that app's user token."
open_url "https://api.slack.com/apps?new_app=1"
step "Create an app 'From scratch', name it, pick your workspace."
step "OAuth & Permissions → Scopes → User Token Scopes (not Bot)."
step "Add scopes for the tools you want. The full set mcp.slack.com accepts:"
note "  search:read.public search:read.private search:read.im search:read.mpim"
note "  search:read.files search:read.users users:read users:read.email"
note "  channels:read channels:history channels:write chat:write"
note "  groups:read groups:history groups:write im:read im:history im:write"
note "  mpim:read mpim:history mpim:write reactions:read reactions:write"
note "  canvases:read canvases:write lists:read lists:write files:read files:write emoji:read"
step "Click 'Install to Workspace' and approve — a workspace admin may need to approve first."
step "Back on OAuth & Permissions, copy the 'User OAuth Token' (starts xoxp-)."
ask_token SLACK_TOKEN "omp/slack-mcp-user-token" "Paste the Slack user OAuth token:"
if store_keychain "omp/slack-mcp-user-token" "$SLACK_TOKEN"; then
	if probe_mcp "https://mcp.slack.com/mcp" "omp/slack-mcp-user-token"; then
		wire_header slack "omp/slack-mcp-user-token"
		note "slack was enabled by that wiring; it has no OAuth route to fall back on."
	else
		warn "slack stays disabled — it has no OAuth fallback, so a bad token means no slack"
		SKIPPED+=("slack: endpoint rejected the token, server left disabled")
	fi
fi

# ── Stage 4 ───────────────────────────────────────────────────────────────
stage "Alchemy, and what is left"
say "Alchemy's MCP is OAuth-only: no API key, no static token, nothing to store."
step "After restarting omp, run: /mcp reauth alchemy"
note "Its credential lands in this profile's auth storage, not in mcp.json."
printf '\n'
say "Keychain items now present:"
for svc in omp/notion-mcp-token omp/sentry-mcp-token omp/slack-mcp-user-token; do
	if security find-generic-password -s "$svc" -a omp >/dev/null 2>&1; then
		printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$svc"
	else
		printf '  %s·%s %s %s(absent → that server stays on OAuth)%s\n' "$DIM" "$RESET" "$svc" "$DIM" "$RESET"
	fi
done
printf '\n'
say "For any server that got wired above, drop its now-superseded OAuth"
say "credential from local storage with: /mcp unauth <server>"
warn "Config changes need an omp restart before any of this is live."

finish
